#+title: Machine Learning Tutorials
#+date: 2017-03-29
** Machine Learning
1. Dr Jason Browniee's
   [[http://machinelearningmastery.com/start-here/][Machine Learning
   Mastery]] is for everybody, even total beginners, who've heard the
   hype about ML, and want to get in on the action. It's step by step,
   simple and very easy to follow.

2. Once one has done quite a few chapters into Machine Learning Mastery
   it's good to check out ujjwalkarn's Github list of
   [[https://github.com/ujjwalkarn/Machine-Learning-Tutorials][Machine
   Learning and Deep Learning Tutorials]].

** Neural Networks
1. If you're totally new to neural networks, Andrej Karpathy's
   [[http://karpathy.github.io/neuralnets/][Hacker's Guide to Neural
   Networks]] is hands down the best. No complex formulas, no jargon,
   just plain and simple concepts demonstrated with code (which you
   should definitely rewrite to fully understand).

2. [[http://www.ai-junkie.com/ga/intro/gat1.html][Genetic Algorithms]]
   for tuning the weights of an existing neural network: pretty cool,
   although this is just one way to train a neural network. I'd imagine
   one would use the gradients in Karpathy's tutorial to get to a pretty
   well trained neural network, and then use the genetic algorithm to
   make small improvement tweaks from there.


